In [13]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')
c=np.zeros((3,4))

c

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
a=np.array([[7,8,9],[4,5,6],[1,2,3]])
a

array([[7, 8, 9],
       [4, 5, 6],
       [1, 2, 3]])

In [17]:
a[:,1]

array([8, 5, 2])

In [20]:
a[1:]

array([[4, 5, 6],
       [1, 2, 3]])

In [21]:
a=np.arange(1,26).reshape(5,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [22]:
a[:,[0,4]]

array([[ 1,  5],
       [ 6, 10],
       [11, 15],
       [16, 20],
       [21, 25]])

In [24]:
a[[1,2],:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [25]:
a[[1,2], [3,4]]

array([ 9, 15])

In [ ]:
#axis 

In [28]:
a=np.random.randint(0,100,25).reshape(5,5)
a

array([[14, 97, 98, 91, 51],
       [37, 37, 93, 10, 23],
       [18, 13, 56, 85, 27],
       [53, 33, 89, 20, 64],
       [85,  9, 65, 90, 87]])

In [29]:
#colum-wise maximum value
a.min(axis=0)

array([14,  9, 56, 10, 23])

In [38]:
#row-wise maximum value
a.max(axis=1)
a


array([[14, 51, 91, 97, 98],
       [10, 23, 37, 37, 93],
       [13, 18, 27, 56, 85],
       [20, 33, 53, 64, 89],
       [ 9, 65, 85, 87, 90]])

In [43]:
a.sum(axis=0)

array([ 66, 190, 293, 341, 455])

In [52]:
#sqrt for squre root

np.sqrt(a)
np.square(a)

array([[ 196, 2601, 8281, 9409, 9604],
       [ 100,  529, 1369, 1369, 8649],
       [ 169,  324,  729, 3136, 7225],
       [ 400, 1089, 2809, 4096, 7921],
       [  81, 4225, 7225, 7569, 8100]], dtype=int32)

In [53]:
np.cumsum(a)

array([  14,   65,  156,  253,  351,  361,  384,  421,  458,  551,  564,
        582,  609,  665,  750,  770,  803,  856,  920, 1009, 1018, 1083,
       1168, 1255, 1345], dtype=int32)

In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4])

print(arr[2] + arr[3]) 

7


In [57]:
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr)

print(arr[0, 1, 2]) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
6


In [ ]:
a=np.array([1,2,3],[4,5,6])

In [60]:
a=np.array( [[2,6,9],[8,6,7]])
b=np.array( [[5,5,4],[7,3,1]])
print(a)
print(b)
np.hstack((a,b))
np.vstack((a,b))

[[2 6 9]
 [8 6 7]]
[[5 5 4]
 [7 3 1]]


array([[2, 6, 9],
       [8, 6, 7],
       [5, 5, 4],
       [7, 3, 1]])